version: '3.9'

services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .env:/app/.env

volumes:
  myenv:
    external: true
